package com.luanvan.luanvanbackend.repositories;

import com.luanvan.luanvanbackend.entities.AvailabilitySlot;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.LocalDateTime;
import java.util.List;

@Repository
public interface AvailabilitySlotRepository extends JpaRepository<AvailabilitySlot, Long> {
    List<AvailabilitySlot> findByDoctorDoctorId(Long doctorId);
    
    Page<AvailabilitySlot> findByDoctorDoctorId(Long doctorId, Pageable pageable);
    
    List<AvailabilitySlot> findByDoctorDoctorIdAndDate(Long doctorId, LocalDate date);
    
    List<AvailabilitySlot> findByDoctorDoctorIdAndDateBetween(Long doctorId, LocalDate startDate, LocalDate endDate);
    
    // Available slots only methods
    List<AvailabilitySlot> findByDoctorDoctorIdAndStatus(Long doctorId, AvailabilitySlot.SlotStatus status);
    
    Page<AvailabilitySlot> findByDoctorDoctorIdAndStatus(Long doctorId, AvailabilitySlot.SlotStatus status, Pageable pageable);
    
    List<AvailabilitySlot> findByDoctorDoctorIdAndDateAndStatus(Long doctorId, LocalDate date, AvailabilitySlot.SlotStatus status);
    
    List<AvailabilitySlot> findByDoctorDoctorIdAndDateBetweenAndStatus(Long doctorId, LocalDate startDate, LocalDate endDate, AvailabilitySlot.SlotStatus status);
    
    List<AvailabilitySlot> findByDateAndStatus(LocalDate date, AvailabilitySlot.SlotStatus status);
    
    List<AvailabilitySlot> findByDateBetweenAndStatus(LocalDate startDate, LocalDate endDate, AvailabilitySlot.SlotStatus status);
    
    List<AvailabilitySlot> findByClinicClinicId(Long clinicId);
    
    @Query("SELECT a FROM AvailabilitySlot a " +
           "WHERE a.doctor.doctorId = :doctorId AND a.date = :date " +
           "AND ((a.startTime <= :endTime AND a.endTime >= :startTime))")
    List<AvailabilitySlot> findOverlappingSlots(@Param("doctorId") Long doctorId, 
                                               @Param("date") LocalDate date,
                                               @Param("startTime") LocalTime startTime,
                                               @Param("endTime") LocalTime endTime);
    
    @Query("SELECT a FROM AvailabilitySlot a " +
           "JOIN a.doctor d JOIN d.specialties ds " +
           "WHERE ds.specialty.specialtyId = :specialtyId AND a.date = :date AND a.status = 'AVAILABLE'")
    List<AvailabilitySlot> findAvailableSlotsBySpecialtyAndDate(@Param("specialtyId") Long specialtyId, 
                                                               @Param("date") LocalDate date);
    
    // Enhanced methods for specialty-based conflict detection
    List<AvailabilitySlot> findByDoctorDoctorIdAndSpecialtySpecialtyId(Long doctorId, Long specialtyId);
    
    List<AvailabilitySlot> findByDoctorDoctorIdAndSpecialtySpecialtyIdAndDate(Long doctorId, Long specialtyId, LocalDate date);
    
    List<AvailabilitySlot> findByDoctorDoctorIdAndSpecialtySpecialtyIdAndDateBetween(Long doctorId, Long specialtyId, LocalDate startDate, LocalDate endDate);
    
    // Conflict detection queries
    @Query("SELECT a FROM AvailabilitySlot a WHERE a.doctor.doctorId = :doctorId " +
           "AND a.date = :date AND a.startTime = :startTime " +
           "AND a.status = 'AVAILABLE' AND a.specialty.specialtyId != :excludeSpecialtyId")
    List<AvailabilitySlot> findConflictingSlots(
        @Param("doctorId") Long doctorId,
        @Param("date") LocalDate date, 
        @Param("startTime") LocalTime startTime,
        @Param("excludeSpecialtyId") Long excludeSpecialtyId);
    
    @Query("SELECT a FROM AvailabilitySlot a WHERE a.doctor.doctorId = :doctorId " +
           "AND a.date = :date AND a.startTime >= :startTime AND a.startTime < :endTime " +
           "AND a.status = 'AVAILABLE' AND a.specialty.specialtyId != :excludeSpecialtyId")
    List<AvailabilitySlot> findConflictingSlotsInTimeRange(
        @Param("doctorId") Long doctorId,
        @Param("date") LocalDate date,
        @Param("startTime") LocalTime startTime,
        @Param("endTime") LocalTime endTime,
        @Param("excludeSpecialtyId") Long excludeSpecialtyId);
    
    // Auto-generated slots queries
    List<AvailabilitySlot> findByAutoGeneratedTrue();
    
    List<AvailabilitySlot> findByDoctorDoctorIdAndAutoGeneratedTrue(Long doctorId);
    
    List<AvailabilitySlot> findByCreatedFromShiftId(Long shiftId);
    
    @Query("SELECT a FROM AvailabilitySlot a WHERE a.doctor.doctorId = :doctorId " +
           "AND a.date = :date AND a.createdFromShiftId = :shiftId")
    List<AvailabilitySlot> findByDoctorAndDateAndShift(
        @Param("doctorId") Long doctorId,
        @Param("date") LocalDate date,
        @Param("shiftId") Long shiftId);
    
    // Batch operations for slot management
    @Query("SELECT a FROM AvailabilitySlot a WHERE a.doctor.doctorId = :doctorId " +
           "AND a.specialty.specialtyId = :specialtyId AND a.date BETWEEN :startDate AND :endDate " +
           "ORDER BY a.date, a.startTime")
    List<AvailabilitySlot> findScheduleByDoctorSpecialtyAndDateRange(
        @Param("doctorId") Long doctorId,
        @Param("specialtyId") Long specialtyId,
        @Param("startDate") LocalDate startDate,
        @Param("endDate") LocalDate endDate);
    
    // Performance optimized count queries
    @Query("SELECT COUNT(a) FROM AvailabilitySlot a WHERE a.doctor.doctorId = :doctorId " +
           "AND a.date = :date AND a.status = 'AVAILABLE'")
    Long countAvailableSlotsByDoctorAndDate(@Param("doctorId") Long doctorId, @Param("date") LocalDate date);
    
    @Query("SELECT COUNT(a) FROM AvailabilitySlot a WHERE a.doctor.doctorId = :doctorId " +
           "AND a.specialty.specialtyId = :specialtyId AND a.date = :date AND a.status = 'AVAILABLE'")
    Long countAvailableSlotsByDoctorSpecialtyAndDate(
        @Param("doctorId") Long doctorId,
        @Param("specialtyId") Long specialtyId,
        @Param("date") LocalDate date);
    
    // Delete operations
    void deleteByDoctorDoctorIdAndCreatedFromShiftId(Long doctorId, Long shiftId);
    
    @Query("DELETE FROM AvailabilitySlot a WHERE a.doctor.doctorId = :doctorId " +
           "AND a.specialty.specialtyId = :specialtyId AND a.date BETWEEN :startDate AND :endDate " +
           "AND a.autoGenerated = true")
    void deleteAutoGeneratedSlotsByDoctorSpecialtyAndDateRange(
        @Param("doctorId") Long doctorId,
        @Param("specialtyId") Long specialtyId,
        @Param("startDate") LocalDate startDate,
        @Param("endDate") LocalDate endDate);
    
    List<AvailabilitySlot> findByDoctorDoctorIdAndDateAndStartTimeAndEndTime(Long doctorId, LocalDate date, LocalTime startTime, LocalTime endTime);
    
    // Tìm slot theo doctor, date và startTime (cho ghi đè tuyệt đối)
    List<AvailabilitySlot> findByDoctorDoctorIdAndDateAndStartTime(Long doctorId, LocalDate date, LocalTime startTime);

    @Query("SELECT s FROM AvailabilitySlot s WHERE " +
            "FUNCTION('TIMESTAMP', s.date, s.endTime) < :expiryDateTime " +
            "AND s.status IN :statuses")
    List<AvailabilitySlot> findExpiredSlotsWithStatuses(@Param("expiryDateTime") LocalDateTime expiryDateTime, @Param("statuses") List<AvailabilitySlot.SlotStatus> statuses);
}