package com.luanvan.luanvanbackend.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class AvailabilitySlotResponseDTO {
    
    @JsonProperty("slotId")
    private Long slotId;
    
    @JsonProperty("doctorId")
    private Long doctorId;
    
    @JsonProperty("doctorName")
    private String doctorName;
    
    @JsonProperty("date")
    private LocalDate date;
    
    @JsonProperty("startTime")
    private LocalTime startTime;
    
    @JsonProperty("endTime")
    private LocalTime endTime;
    
    @JsonProperty("status")
    private String status;
    
    @JsonProperty("isAvailable")
    private Boolean isAvailable;
    
    @JsonProperty("clinicId")
    private Long clinicId;
    
    @JsonProperty("clinicName")
    private String clinicName;
    
    @JsonProperty("specialtyId")
    private Long specialtyId;
    
    @JsonProperty("specialtyName")
    private String specialtyName;
    
    @JsonProperty("slotDurationMinutes")
    private Integer slotDurationMinutes;
    
    @JsonProperty("autoGenerated")
    private Boolean autoGenerated;
    
    @JsonProperty("notes")
    private String notes;
    
    @JsonProperty("createdFromShiftId")
    private Long createdFromShiftId;
    
    // Utility methods
    public boolean isAvailable() {
        return "AVAILABLE".equals(this.status);
    }
    
    public boolean isAutoGenerated() {
        return this.autoGenerated != null && this.autoGenerated;
    }
} 