package com.luanvan.luanvanbackend.entities;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
@Table(name = "availability_slots")
public class AvailabilitySlot {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long slotId;
    
    @ManyToOne
    @JoinColumn(name = "doctor_id")
    private Doctor doctor;
    
    private LocalDate date;
    private LocalTime startTime;
    private LocalTime endTime;
    
    @Enumerated(EnumType.STRING)
    private SlotStatus status;
    
    @ManyToOne
    @JoinColumn(name = "clinic_id")
    private Clinic clinic;
    
    // New fields for enhanced schedule management
    @ManyToOne
    @JoinColumn(name = "specialty_id")
    private Specialty specialty; // Liên kết với chuyên khoa
    
    @Column(name = "slot_duration_minutes")
    private Integer slotDurationMinutes = 30; // Thời lượng slot (mặc định 30 phút)
    
    @Column(name = "auto_generated")
    private Boolean autoGenerated = false; // Đánh dấu slot được tạo tự động từ ca làm việc
    
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes; // Ghi chú của bác sĩ cho slot
    
    @Column(name = "created_from_shift_id")
    private Long createdFromShiftId; // ID của StandardWorkShift mà slot này được tạo từ

    @OneToMany(mappedBy = "slot")
    @JsonIgnore
    private List<Appointment> appointments;
    
    public enum SlotStatus {
        AVAILABLE, BOOKED, CANCELLED_BY_CLINIC, ON_LEAVE
    }
    
    public AvailabilitySlot() {
    }
    
    public AvailabilitySlot(Long slotId, Doctor doctor, LocalDate date, LocalTime startTime, LocalTime endTime, SlotStatus status, Clinic clinic) {
        this.slotId = slotId;
        this.doctor = doctor;
        this.date = date;
        this.startTime = startTime;
        this.endTime = endTime;
        this.status = status;
        this.clinic = clinic;
    }
    
    // Enhanced constructor for new fields
    public AvailabilitySlot(Doctor doctor, LocalDate date, LocalTime startTime, LocalTime endTime, 
                           SlotStatus status, Clinic clinic, Specialty specialty, Integer slotDurationMinutes, 
                           Boolean autoGenerated, Long createdFromShiftId) {
        this.doctor = doctor;
        this.date = date;
        this.startTime = startTime;
        this.endTime = endTime;
        this.status = status;
        this.clinic = clinic;
        this.specialty = specialty;
        this.slotDurationMinutes = slotDurationMinutes;
        this.autoGenerated = autoGenerated;
        this.createdFromShiftId = createdFromShiftId;
    }
    
    public Long getSlotId() {
        return slotId;
    }
    
    public void setSlotId(Long slotId) {
        this.slotId = slotId;
    }
    
    public Doctor getDoctor() {
        return doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    
    public LocalDate getDate() {
        return date;
    }
    
    public void setDate(LocalDate date) {
        this.date = date;
    }
    
    public LocalTime getStartTime() {
        return startTime;
    }
    
    public void setStartTime(LocalTime startTime) {
        this.startTime = startTime;
    }
    
    public LocalTime getEndTime() {
        return endTime;
    }
    
    public void setEndTime(LocalTime endTime) {
        this.endTime = endTime;
    }
    
    public SlotStatus getStatus() {
        return status;
    }
    
    public void setStatus(SlotStatus status) {
        this.status = status;
    }
    
    public Clinic getClinic() {
        return clinic;
    }
    
    public void setClinic(Clinic clinic) {
        this.clinic = clinic;
    }
    
    // New getters and setters
    public Specialty getSpecialty() {
        return specialty;
    }
    
    public void setSpecialty(Specialty specialty) {
        this.specialty = specialty;
    }
    
    public Integer getSlotDurationMinutes() {
        return slotDurationMinutes;
    }
    
    public void setSlotDurationMinutes(Integer slotDurationMinutes) {
        this.slotDurationMinutes = slotDurationMinutes;
    }
    
    public Boolean getAutoGenerated() {
        return autoGenerated;
    }
    
    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }
    
    public String getNotes() {
        return notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    
    public Long getCreatedFromShiftId() {
        return createdFromShiftId;
    }
    
    public void setCreatedFromShiftId(Long createdFromShiftId) {
        this.createdFromShiftId = createdFromShiftId;
    }

    public List<Appointment> getAppointments() {
        return appointments;
    }

    public void setAppointments(List<Appointment> appointments) {
        this.appointments = appointments;
    }
    
    // Utility methods
    public boolean isAvailable() {
        return this.status == SlotStatus.AVAILABLE;
    }
    
    public boolean isAutoGenerated() {
        return this.autoGenerated != null && this.autoGenerated;
    }
}
