package com.luanvan.luanvanbackend.mappers;

import com.luanvan.luanvanbackend.dto.AvailabilitySlotResponseDTO;
import com.luanvan.luanvanbackend.entities.AvailabilitySlot;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.stream.Collectors;

@Component
public class AvailabilitySlotMapper {
    
    public AvailabilitySlotResponseDTO toResponseDTO(AvailabilitySlot slot) {
        if (slot == null) {
            return null;
        }
        
        AvailabilitySlotResponseDTO dto = new AvailabilitySlotResponseDTO();
        dto.setSlotId(slot.getSlotId());
        dto.setDoctorId(slot.getDoctor() != null ? slot.getDoctor().getDoctorId() : null);
        dto.setDoctorName(slot.getDoctor() != null && slot.getDoctor().getUser() != null ? 
            slot.getDoctor().getUser().getFullName() : null);
        dto.setDate(slot.getDate());
        dto.setStartTime(slot.getStartTime());
        dto.setEndTime(slot.getEndTime());
        dto.setStatus(slot.getStatus() != null ? slot.getStatus().name() : null);
        dto.setIsAvailable("AVAILABLE".equals(slot.getStatus() != null ? slot.getStatus().name() : null));
        dto.setClinicId(slot.getClinic() != null ? slot.getClinic().getClinicId() : null);
        dto.setClinicName(slot.getClinic() != null ? slot.getClinic().getName() : null);
        dto.setSpecialtyId(slot.getSpecialty() != null ? slot.getSpecialty().getSpecialtyId() : null);
        dto.setSpecialtyName(slot.getSpecialty() != null ? slot.getSpecialty().getName() : null);
        dto.setSlotDurationMinutes(slot.getSlotDurationMinutes());
        dto.setAutoGenerated(slot.getAutoGenerated());
        dto.setNotes(slot.getNotes());
        dto.setCreatedFromShiftId(slot.getCreatedFromShiftId());
        
        return dto;
    }
    
    public List<AvailabilitySlotResponseDTO> toResponseDTOList(List<AvailabilitySlot> slots) {
        if (slots == null) {
            return null;
        }
        
        return slots.stream()
                .map(this::toResponseDTO)
                .collect(Collectors.toList());
    }
} 